# Clase 4: Manejo de Arreglos Multidimensionales con `Numpy`

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**


## Objetivos

- Introducirlos a Numpy y su uso en la ciencia de datos.
- Explorar arreglos multidimensionales y la vectorización de operaciones.


## Motivación


Consideren el siguiente ejemplo:

> **Pregunta ❓:** ¿Cómo le sumamos 1 a cada valor de la lista?


In [ ]:
lista = [1, 4, 5, 7]
lista

In [ ]:
for i in range(len(lista)):
    lista[i] = lista[i] + 1

lista

In [ ]:
[i+1 for i in lista]

> **Pregunta ❓:** ¿Cómo le sumamos 1 a cada valor de la matriz?


In [ ]:
matriz = [
    [1, 4, 5, 7],
    [1, 1, 0, 0],
    [7, 7, 2, 5],
]
matriz

In [ ]:
for i in range(len(matriz)):
    for j in range(len(matriz[0])):
        matriz[i][j] += 1

In [ ]:
matriz

> **Pregunta ❓:** Qué pasa si tenemos una lista de matrices y a cada elemento queremos sumarle 1?


In [ ]:
matriz = [
    [
        [1, 4, 5, 7],
        [1, 1, 0, 0],
        [7, 7, 2, 5],
    ],
    [
        [4, 7, 8, 10],
        [4, 4, 3, 3],
        [10, 10, 5, 8],
    ],
]

In [ ]:
for i in range(len(matriz)):
    for j in range(len(matriz[0])):
        for k in range(len(matriz[0][0])):
            matriz[i][j][k] += 1

> **Pregunta ❓:** Y podríamos tener algo como `matriz + 1`?


In [ ]:
matriz + 1

## Numpy


[NumPy (Numerical Python)](http://www.numpy.org/) es el módulo fundamental para la computación científica en Python. Numpy es un módulo que provee **arreglos multi-dimensionales homogeneos** (i.e., del mismo tipo de datos) y una gran gama de operaciones optimizadas que aplican sobre estos, tales como álgebra lineal, E/S (I/O), estadística básica, simulaciones aleatorias y un gran etc.

Su uso se ha vuelto un estándar en computación científica, en particular en ciencia de datos y machine learning. Su uso es similar a otras herramientas matemáticas como MATLAB, pero esta es **Open Source 👍**.


### Ejemplos de Aplicaciones

<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/numpy_case_studies.jpg" alt="Casos de estudio" style="width: 800px;"/>
</div>


### Ecosistema

<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/numpy_ecosistema.jpg" alt="Ecosistema de Numpy" style="width: 800px;"/>
</div>


### La clase `ndarray`

**Arreglo** (según wikipedia):

> Es a una zona de almacenamiento contiguo (en la memoria RAM) que contiene una serie de elementos del mismo tipo.

<br>

<div align='center'>
<img src='https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/array.png' width=800>
</div>

<div align='center'>
    Fuente: <a href='https://medium.com/@akedalat/how-arrays-allocate-memory-a9bc93c0ad45'> https://medium.com/@akedalat/how-arrays-allocate-memory-a9bc93c0ad45</a>
</div>

<br>

El núcleo de `numpy` es el objeto ndarray. Este objeto encapsula **arreglos n-dimensionales** de **tipos de datos homogeneos** e implementa **rutinas precompiladas** para el calculo de operaciones.

Algunas de las características de estos arreglos.

| Arreglos de tamaño fijo.                                                                                                                                               | Arreglos del mismo tipo de datos.                                                                                                  | Provee operaciones matemáticas sobre largos conjuntos de datos.                                                           |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------- |
| A diferencia de las listas de python que pueden crecer dinámicamente, los arreglos de numpy son estáticos. Modificar el tamaño de un arreglo implicará crear uno nuevo | Tipos de datos distintos tienen tamaños distintos. Al tener tipos de datos de igual tamaño, se puede manejar mejor la memoria RAM. | Los módulos precompilados ofrecen operaciones más eficientes sobre arreglos numpy que su equivalente de listas en python. |


---


### Vectorización

La vectorización es la ausencia de cualquier ciclo o indexado explícito en el código. Todo se hace a través de funciones que operan "detrás de escenas".

**Ventajas**

- El código vectorizado es mas conciso y fácil de leer.

- Menos lineas de código = Menos bugs.

- La notación vectorizada "recuerda" en algo a la notación matemática. (Piensen en una suma de dos vectores implementado en for con respecto un `a + b`).


```python
# pseudocódigo que nos permite comparar ambos enfoques: ciclos vs vectorización.

a = [1, 2, 3, 4, ...]
b = [1, 2, 3, 4, ...]

```


```python
# 1.- Ejemplo con ciclos.
c = []
for i in range(len(a)):
    suma = a[i] + b[i]
    c.append(suma)

```


```python
# 2.- Ejemplo vectorizado.
c = a + b
```


## Primeros Pasos


Importamos comunmente `numpy` usando el alias `np`.


In [1]:
!uv add numpy

Resolved 47 packages in 1ms
Audited 41 packages in 4ms


In [2]:
# alias comun es np
import numpy as np

### Creación de arrays

Existen varias formas de crear arreglos.


##### Inicializar a partir de listas


In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

![Ejemplo ndarray](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/np_array.png)


##### Crear _arrays_ llenos de ceros


In [4]:
b = np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Crear _arrays_ de 1


In [5]:
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Y arreglos con valores aleatorios

Esto genera una matriz en donde cada elemento es un número $ \sim \text{unif}([0,1])$


In [6]:
np.random.rand(5)

array([0.25854868, 0.98358681, 0.97644317, 0.79787096, 0.77936725])

##### También podemos crear matrices de forma muy sencilla


In [7]:
e = np.ones((5, 6))
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Como también a partir de listas


In [8]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12],
    ]
)

m


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

> **Pregunta ❓** : ¿Qué sucederá con el siguiente código?

In [9]:
m2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7,],
    ]
)
m2

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

> **Pregunta ❓** : ¿Qué sucede con el siguiente código?


In [10]:
np.array(["hola", "chao"])

array(['hola', 'chao'], dtype='<U4')

In [11]:
np.array(
    [
        ["h", "o", "l", "a"],
        ["c", "h", "a", "o"],
    ]
)


array([['h', 'o', 'l', 'a'],
       ['c', 'h', 'a', 'o']], dtype='<U1')

## Propiedades ndarray

### Triángulo 📐

De aquí en adelante definiremos una matriz que contendrá los puntos que conforman un triángulo y estaremos trabajando sobre esta.

In [12]:
import numpy as np

puntos = np.array(
    [
        [0, 0],
        [1, 2],
        [2, 0],
        [0, 0],
    ]
)

puntos

array([[0, 0],
       [1, 2],
       [2, 0],
       [0, 0]])

> **Pregunta ❓**: ¿Qué interpretación le podríamos dar a los valores mostrados en el arreglo anterior?


In [ ]:
# para instalarlo en colab
!uv add plotly nbformat ipykernel

Resolved 47 packages in 2ms
Audited 41 packages in 5ms


In [14]:
import plotly.graph_objects as go


def plot_triangulo(puntos):
    fig = go.Figure(go.Scatter(x=puntos[:, 0], y=puntos[:, 1], fill="toself"))
    fig.update_layout(height=500, width=500).show()

In [15]:
plot_triangulo(puntos)

In [16]:
puntos

array([[0, 0],
       [1, 2],
       [2, 0],
       [0, 0]])

#### Axes

En `numpy`, las dimensiones son llamadas **_axes_**.

La matriz que vimos antes (`puntos`) es un conjunto de cuatro puntos bidimensionales. Es decir, la matriz puede ser considerada como una lista de puntos, los cuales cuentan con un valor para el eje X y uno para el eje Y.

Notemos que:

- Un punto `[0, 0]` es un arreglo de una sola dimensión (un solo axe).
- Un conjunto de dos puntos `[[0, 0], [1, 2]],` es un arreglo de dos dimensiones (dos axes).

> **Pregunta ❓**: `[[[0, 0], [1, 2]], [[3, 4], [5, 6]], [[7, 8], [9, 10]]]` ¿Cuántos axes tiene?


#### Atributos de la clase ndarray


In [ ]:
puntos

##### `ndim`

Podemos acceder al número de dimensiones o axes a través del atributo `ndim`


In [17]:
puntos.ndim

2

##### `shape`

Shape es una tupla que indica el tamaño de cada dimension. Nota que la tupla tiene la misma cantidad de elementos que el número de dimensiones.

En nuesto ejemplo, la dimensión 1 tiene tamaño 4 (4 puntos) y la segunda dimensión tiene 2 (coordenadas).


In [18]:
puntos.shape

(4, 2)

In [19]:
puntos

array([[0, 0],
       [1, 2],
       [2, 0],
       [0, 0]])

##### `size`

Es el número de elementos totales en nuestro arreglo. Se calcula como la **multiplicación** de los tamaños de cada dimensión.


In [20]:
puntos.size

8

##### `dtype`

El tipo de datos que tiene nuestro arreglo


In [21]:
puntos.dtype

dtype('int64')

### Datos sobre múltiples dimensiones

Supongamos que el triángulo va creciendo aleatoriamente según pasa el tiempo.

Es decir que tendrémos para cada $t$, un conjunto de cuatro puntos distintos.


In [25]:
puntos = np.array(
    [
        [0, 0],
        [1, 2],
        [2, 0],
        [0, 0],
    ]
)

print(puntos)
plot_triangulo(puntos)

[[0 0]
 [1 2]
 [2 0]
 [0 0]]


In [26]:
puntos_t1 = np.round(puntos + np.random.uniform(low=-1, high=1, size=(4, 2)), 2)
puntos_t1[-1, :] = puntos_t1[0, :]  # aseguramos que la figura producida termine al incio y sea cerrada.
print(puntos_t1)
plot_triangulo(puntos_t1)

[[-0.55  0.64]
 [ 0.3   1.67]
 [ 1.87 -0.3 ]
 [-0.55  0.64]]


In [27]:
puntos_t2 = np.round(puntos_t1 + np.random.uniform(low=-1, high=1, size=(4, 2)), 2)
puntos_t2[-1, :] = puntos_t2[0, :]  # aseguramos que la figura producida termine al incio y sea cerrada.
print(puntos_t2)
plot_triangulo(puntos_t2)

[[ 0.28  1.38]
 [-0.31  1.23]
 [ 2.68  0.11]
 [ 0.28  1.38]]


In [28]:
puntos_t3 = np.round(puntos_t2 + np.random.uniform(low=-1, high=1, size=(4, 2)), 2)
puntos_t3[-1, :] = puntos_t3[0, :]  # aseguramos que la figura producida termine al incio y sea cerrada.
print(puntos_t3)
plot_triangulo(puntos_t3)

[[ 0.12  1.97]
 [ 0.02  0.56]
 [ 2.89 -0.69]
 [ 0.12  1.97]]


In [29]:
puntos_t4 = np.round(puntos_t3 + np.random.uniform(low=-1, high=1, size=(4, 2)), 2)
puntos_t4[-1, :] = puntos_t4[0, :]  # aseguramos que la figura producida termine al incio y sea cerrada.
print(puntos_t4)
plot_triangulo(puntos_t4)

[[-0.58  1.87]
 [-0.68  1.41]
 [ 2.64 -0.33]
 [-0.58  1.87]]


> **Pregunta ❓**: ¿Cómo podemos agregar el tiempo a nuestro conjunto de datos?


La forma de agregar esta variable es agregar una nueva dimensión al arreglo.

Es decir, ahora tener las dimensiones serán: `(tiempo, puntos del tetraedro, valores de X e Y)`


In [30]:
puntos_t = np.array([
    puntos,
    puntos_t1,
    puntos_t2,
    puntos_t3,
    puntos_t4,
])
puntos_t

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[-0.55,  0.64],
        [ 0.3 ,  1.67],
        [ 1.87, -0.3 ],
        [-0.55,  0.64]],

       [[ 0.28,  1.38],
        [-0.31,  1.23],
        [ 2.68,  0.11],
        [ 0.28,  1.38]],

       [[ 0.12,  1.97],
        [ 0.02,  0.56],
        [ 2.89, -0.69],
        [ 0.12,  1.97]],

       [[-0.58,  1.87],
        [-0.68,  1.41],
        [ 2.64, -0.33],
        [-0.58,  1.87]]])

In [31]:
puntos_t.shape

(5, 4, 2)

In [32]:
puntos_t.ndim

3

Comunmente, los arreglos de más de dos dimensiones son conocidos como **<u>tensores</u>**.


> **Pregunta ❓**: ¿Qué son las imágenes y cómo podemos modelarlas usando un arreglo?


Ejemplo de imagen 8x8 en blanco negro.


In [33]:
imagen = (
    np.array(
        [
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
            [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        dtype="uint8",
    )
    * 255
)

In [34]:
import plotly.express as px

px.imshow(imagen, binary_string=True)

Por lo general, las imágenes tienen 3 canales: Rojo Verde y Azul (Red, Green and Blue = **RGB**).


In [39]:
imagen = [
    [[1, 2, 33], [3, 122, 22], [2, 122, 1], ...],
    [[...], [...], [...], ...],
    [[...], [...], [...], ...],
    [[...], [...], [...], ...],
    [[...], [...], [...], ...],
    [[...], [...], [...], ...],
]



> **Pregunta ❓**: ¿Y los videos?



## Indexado

Permite acceder a ciertos valores del arreglo. El indexado es muy similar a las listas de python.

![Indexado](https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/np_indexing.png)

<center>Fuente: https://numpy.org/devdocs/user/absolute_beginners.html </center>


**Recordar**: En nuestro ejercicio, `puntos_t` tiene 3 dimensiones: `(tiempo, puntos del tetraedro, valores X e Y)`


In [40]:
puntos_t

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[-0.55,  0.64],
        [ 0.3 ,  1.67],
        [ 1.87, -0.3 ],
        [-0.55,  0.64]],

       [[ 0.28,  1.38],
        [-0.31,  1.23],
        [ 2.68,  0.11],
        [ 0.28,  1.38]],

       [[ 0.12,  1.97],
        [ 0.02,  0.56],
        [ 2.89, -0.69],
        [ 0.12,  1.97]],

       [[-0.58,  1.87],
        [-0.68,  1.41],
        [ 2.64, -0.33],
        [-0.58,  1.87]]])

### Ejercicios de Indexación


1.- Obtener el primer triángulo, en el tiempo 0.


In [41]:
puntos_t[0]

array([[0., 0.],
       [1., 2.],
       [2., 0.],
       [0., 0.]])

2.- Obtener el primer y segundo triángulo (tiempos 0 y 1)


In [42]:
puntos_t[:2]

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[-0.55,  0.64],
        [ 0.3 ,  1.67],
        [ 1.87, -0.3 ],
        [-0.55,  0.64]]])

In [43]:
puntos_t[0:2]

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[-0.55,  0.64],
        [ 0.3 ,  1.67],
        [ 1.87, -0.3 ],
        [-0.55,  0.64]]])

3.- Obtener el primer y el tercer triángulo (tiempos 0 y 2)


In [44]:
puntos_t[[0, 2]]

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[ 0.28,  1.38],
        [-0.31,  1.23],
        [ 2.68,  0.11],
        [ 0.28,  1.38]]])

4.- Obtener el primer y segundo vértice del triángulo en el tiempo 0.


In [45]:
puntos_t[0][0:2]

array([[0., 0.],
       [1., 2.]])

5.- Resumir la operación anterior en un solo indexador


In [46]:
puntos_t[0, 0:2]

array([[0., 0.],
       [1., 2.]])

6.- Obtener solo los puntos del eje X de todos los triángulos


In [47]:
puntos_t[:, :, 0]

array([[ 0.  ,  1.  ,  2.  ,  0.  ],
       [-0.55,  0.3 ,  1.87, -0.55],
       [ 0.28, -0.31,  2.68,  0.28],
       [ 0.12,  0.02,  2.89,  0.12],
       [-0.58, -0.68,  2.64, -0.58]])

7.- ¿Qué obtenemos en este caso?


In [48]:
puntos_t[:, 0:1, 1] # eje Y del primer punto de todos los triángulos

array([[0.  ],
       [0.64],
       [1.38],
       [1.97],
       [1.87]])

In [49]:
puntos_t[:, 0:1, 0:2] # eje X e Y del primer punto de todos los triángulos

array([[[ 0.  ,  0.  ]],

       [[-0.55,  0.64]],

       [[ 0.28,  1.38]],

       [[ 0.12,  1.97]],

       [[-0.58,  1.87]]])

In [50]:
puntos_t

array([[[ 0.  ,  0.  ],
        [ 1.  ,  2.  ],
        [ 2.  ,  0.  ],
        [ 0.  ,  0.  ]],

       [[-0.55,  0.64],
        [ 0.3 ,  1.67],
        [ 1.87, -0.3 ],
        [-0.55,  0.64]],

       [[ 0.28,  1.38],
        [-0.31,  1.23],
        [ 2.68,  0.11],
        [ 0.28,  1.38]],

       [[ 0.12,  1.97],
        [ 0.02,  0.56],
        [ 2.89, -0.69],
        [ 0.12,  1.97]],

       [[-0.58,  1.87],
        [-0.68,  1.41],
        [ 2.64, -0.33],
        [-0.58,  1.87]]])

## Operaciones aritméticas y lógicas


#### Operaciones aritméticas

Las operaciones aritméticas siempre operan elemento a elemento (**elementwise**).


In [51]:
a = np.array([20, 30, 40, 50])
b = np.array([0, 1, 2, 3])

In [52]:
a - b

array([20, 29, 38, 47])

In [53]:
a + b

array([20, 31, 42, 53])

In [54]:
b**2

array([0, 1, 4, 9])

In [55]:
10 * b

array([ 0, 10, 20, 30])

##### Operaciones Lógicas


In [56]:
a = np.array([20, 30, 40, 50])
b = np.array([0, 1, 2, 3])

In [57]:
a < b

array([False, False, False, False])

In [58]:
a <= 20

array([ True, False, False, False])

In [59]:
a > 20

array([False,  True,  True,  True])

In [60]:
a == 20

array([ True, False, False, False])

In [64]:
condicion1 = a >= 30
condicion2 = a <= 40

In [65]:
np.logical_and(condicion1, condicion2)  # y lógico

array([False,  True,  True, False])

In [67]:
np.logical_or(condicion1, condicion2)  # o lógico

array([ True,  True,  True,  True])

In [68]:
np.logical_not(condicion1)  # not

array([ True, False, False, False])

**Nota:** Para el caso del producto matricial, se ocupa `@`.


<div align='center'>
    <img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/formula_prod_matricial.jpg" alt="Formula prod matricial" style="width: 700px;"/>
</div>


<div align='center'>
<img src="https://raw.githubusercontent.com/MDS7202/MDS7202/main/recursos/2023-01/07-Numpy/prod_matricial.jpg" alt="Producto Matricial" width=250/>
</div>


In [69]:
A = np.array([[1, 1], [0, 1]])

B = np.array([[2, 0], [3, 4]])

In [71]:
A * B  # elementwise product

array([[2, 0],
       [0, 4]])

In [75]:
A

array([[1, 1],
       [0, 1]])

In [76]:
B

array([[2, 0],
       [3, 4]])

In [ ]:
A @ B  # producto matricial

array([[5, 4],
       [3, 4]])

#### Operaciones sobre los elementos


In [77]:
a

array([20, 30, 40, 50])

In [78]:
a.sum()

np.int64(140)

In [79]:
a.min()

np.int64(20)

In [80]:
a.max()

np.int64(50)

> **Pregunta ❓**: Para el caso de un arreglo de más de una dimensión, qué retornará max?

In [84]:
a = np.array(
    [
        [10, 2, -3],
        [1, 2, 6],
        [7, -9, 9],
    ]
)

a

array([[10,  2, -3],
       [ 1,  2,  6],
       [ 7, -9,  9]])

In [85]:
a.max()

np.int64(10)

Se puede especificar el eje sobre el cuál se ejecutará la acción:

In [86]:
a.max(axis=0)

array([10,  2,  9])

In [87]:
a.max(axis=1)

array([10,  6,  9])

### Queries

Selección de datos por medio de consultas, en este caso lógicas.


In [88]:
a = np.array(
    [
        [10, 2, -3],
        [1, 2, 6],
        [7, -9, 9],
    ]
)

In [89]:
a > 3

array([[ True, False, False],
       [False, False,  True],
       [ True, False,  True]])

In [90]:
mayor3 = a[a > 3]
mayor3

array([10,  6,  7,  9])

> **Pregunta ❓**: ¿Qué implicancia podría tener esta funcionalidad a futuro?


## Funciones Universales

Operaciones elemento a elemento aplicadas a arreglos.

Ejemplo:`sen, cos, exp, sqrt, log, etc...`


In [91]:
B = np.arange(0, 10 , 0.5)
B

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [92]:
exp = np.exp(B)
exp

array([1.00000000e+00, 1.64872127e+00, 2.71828183e+00, 4.48168907e+00,
       7.38905610e+00, 1.21824940e+01, 2.00855369e+01, 3.31154520e+01,
       5.45981500e+01, 9.00171313e+01, 1.48413159e+02, 2.44691932e+02,
       4.03428793e+02, 6.65141633e+02, 1.09663316e+03, 1.80804241e+03,
       2.98095799e+03, 4.91476884e+03, 8.10308393e+03, 1.33597268e+04])

In [93]:
sqrt = np.sqrt(B)
sqrt

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356,
       1.58113883, 1.73205081, 1.87082869, 2.        , 2.12132034,
       2.23606798, 2.34520788, 2.44948974, 2.54950976, 2.64575131,
       2.73861279, 2.82842712, 2.91547595, 3.        , 3.082207  ])

In [94]:
sin = np.sin(B)
sin

array([ 0.        ,  0.47942554,  0.84147098,  0.99749499,  0.90929743,
        0.59847214,  0.14112001, -0.35078323, -0.7568025 , -0.97753012,
       -0.95892427, -0.70554033, -0.2794155 ,  0.21511999,  0.6569866 ,
        0.93799998,  0.98935825,  0.79848711,  0.41211849, -0.07515112])

In [95]:
cos = np.cos(B)
cos

array([ 1.        ,  0.87758256,  0.54030231,  0.0707372 , -0.41614684,
       -0.80114362, -0.9899925 , -0.93645669, -0.65364362, -0.2107958 ,
        0.28366219,  0.70866977,  0.96017029,  0.97658763,  0.75390225,
        0.34663532, -0.14550003, -0.6020119 , -0.91113026, -0.99717216])

In [96]:
log = np.log(B)
log

C:\Users\Legion4\AppData\Local\Temp\ipykernel_12324\3361120997.py:1: RuntimeWarning: divide by zero encountered in log
  log = np.log(B)


array([       -inf, -0.69314718,  0.        ,  0.40546511,  0.69314718,
        0.91629073,  1.09861229,  1.25276297,  1.38629436,  1.5040774 ,
        1.60943791,  1.70474809,  1.79175947,  1.87180218,  1.94591015,
        2.01490302,  2.07944154,  2.14006616,  2.19722458,  2.2512918 ])

In [97]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=B, y=exp, name="exp", mode="lines+markers"))
fig.add_trace(go.Scatter(x=B, y=sqrt, name="sqrt", mode="lines+markers"))
fig.add_trace(go.Scatter(x=B, y=sin, name="sin", mode="lines+markers"))
fig.add_trace(go.Scatter(x=B, y=cos, name="cos", mode="lines+markers"))
fig.add_trace(go.Scatter(x=B, y=log, name="log", mode="lines+markers"))

fig.update_layout(height=600).show()

## Broadcasting

El Broadcasting es como numpy trata las operaciones entre arreglos con diferentes tamaños, como por ejemplo, un escalar por una matriz. A continuación un ejemplo sencillo:


In [98]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [99]:
a * b

array([2., 4., 6.])

In [100]:
a * 2

array([2., 4., 6.])

Si bien hicimos la misma operación, estas se diferencian en que en la primera operación hicimos un arreglo del mismo tamaño para multiplicar elemento a elemento y en la segunda ocupamos el escalar directamente.

Ahora imagínense un arreglo de miles de millones de elementos y tener que multiplicarlos por dos de la primera forma. Obviamente la segúnda forma será mas eficiente y esto es lo que numpy implementa eficientemente a través del _broadcasting_.


![Broadcasting en el ejemplo anterior](https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/04_Numpy/broadcasting_1.png)


El broadcasting no se limita solo a escalares, si no también que podemos usarlos con arreglos. A continuación, un ejemplo de aquello:


![Broadcasting en el ejemplo anterior](https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/04_Numpy/broadcasting_2.png)


En este ejemplo, un caso en donde el broadcasting no funciona, ya que no calzan las dimensiones:


![Broadcasting en el ejemplo anterior](https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/04_Numpy/broadcasting_3.png)


> **Pregunta ❓**: ¿Qué habría que hacer aquí para que esta operación funcione?


In [101]:
a = np.ones((4, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
a * 10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [103]:
a * [10] # se transforma a np.array(10) y se repite hacia abajo y a la derecha hasta completar la dimensión de a, luego se multiplica

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [104]:
a * [10, 20, 30] # se transforma a np.array([10, 20, 30]) y se repite hacia abajo hasta completar la dimensión de a, luego se multiplica

array([[10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.],
       [10., 20., 30.]])

In [105]:
b = np.ones((1,4)) # 4 "columnas"
b

array([[1., 1., 1., 1.]])

In [106]:
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [107]:
b = np.ones((4, 1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [108]:
a + b # se repite b hacia la derecha hasta completar la dimensión de a, luego se suma

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

Más información en el siguiente [link](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy).


### Vistas y Copias


Recuerden que los nombres son referencias!


In [109]:
a = np.array(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
    ]
)

b = a


In [110]:
b[0, 0] = 999
b

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

> **Pregunta ❓**: ¿Qué sucede con a?


In [111]:
a

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

**Copy**


In [112]:
a = np.array(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11],
    ]
)

d = a.copy()

In [113]:
d is a

False

In [114]:
d[0, 0] = 999
d

array([[999,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [115]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Cambio de dimensiones


### Reshape

Permite cambiar la forma del arreglo.

In [116]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
a.shape

(2, 3)

In [118]:
np.reshape(a, (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

No siempre es posible, el cambio de los elementos debe ser consistente con las dimensiones.

In [119]:
np.reshape(a, (7,))

ValueError: cannot reshape array of size 6 into shape (7,)

Veamos otras formas de cambiar la forma de un arreglo.

Primero definimos un arreglo aleatorio.


In [120]:
c = np.random.rand(2,3)
print(c, "\n")
print(c.shape)

[[0.99381992 0.02783781 0.12755301]
 [0.35872312 0.0914326  0.09771129]] 

(2, 3)


### Ravel

Se utiliza para "desenrollar" o "aplanar" un arreglo multidimensional en un arreglo unidimensional

In [121]:
d = c.ravel()
print(d, "\n")
print(d.shape, "\n")

[0.99381992 0.02783781 0.12755301 0.35872312 0.0914326  0.09771129] 

(6,) 



### Transponer un arreglo


`arreglo.T` crea un nuevo arreglo con la transpuesta.

In [122]:
e = c.T
print(e, "\n")
print(e.shape, "\n")

[[0.99381992 0.35872312]
 [0.02783781 0.0914326 ]
 [0.12755301 0.09771129]] 

(3, 2) 



In [123]:
c.reshape(3, 2) # no es lo mismo que hacer reshape!!

array([[0.99381992, 0.02783781],
       [0.12755301, 0.35872312],
       [0.0914326 , 0.09771129]])

### Resize

Cambia las dimensiones en el propio arreglo, rellenando con el mismo arreglo o 0s dependiendo de la sintaxis hasta llegar a la dimensión requerida. No retorna otro arreglo como en caso de `reshape`.


In [124]:
e = np.array([1, 2, 3])
e

array([1, 2, 3])

In [125]:
# usando np.resize()
x = np.resize(e, (1,2))
y = np.resize(e, (5, 4))
print('resize a arreglo de menor tamaño:\n', x)
print('resize a arreglo de mayor tamaño:\n', y)

resize a arreglo de menor tamaño:
 [[1 2]]
resize a arreglo de mayor tamaño:
 [[1 2 3 1]
 [2 3 1 2]
 [3 1 2 3]
 [1 2 3 1]
 [2 3 1 2]]


In [126]:
# usando arreglo.resize()
e.resize(4, 4, refcheck = False)
e

array([[1, 2, 3, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [127]:
e.resize(1, 2, refcheck = False)
e

array([[1, 2]])

### Concatenate

Concatena arreglos en un nuevo arreglo

In [128]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6]])

np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
x = np.array([[1, 2],
              [3, 4]])

z = np.array([[5, 6],
              [7, 8]])

np.concatenate((x, z), axis=0)  # idea: concatenar a las filas

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [131]:
np.concatenate((x, z), axis=1)  # idea: concatenar a las columnas

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Referencias

Recuerden que siempre pueden acudir a la clase grabada de años anteriores:
[Clase 1](https://www.youtube.com/watch?v=bgqOQ2Xrkxs&list=PLIaUi-1jO5b4PztTeatJFQO1QeQwGo3FS&index=7&pp=iAQB) y [Clase 2](https://www.youtube.com/watch?v=tBxejj6L46U&list=PLIaUi-1jO5b4PztTeatJFQO1QeQwGo3FS&index=8&pp=iAQB)